controller:
  image:
    image: ingress-nginx/controller
    tag: "v1.13.4"

  service:
    type: NodePort
    nodePorts:
      http: 30080

  ingressClassResource:
    name: nginx
    default: true

  extraEnvs:
    - name: TZ
      value: Asia/Seoul

  extraArgs:
    default-ssl-certificate: "nginx-static/nginx-tls"

  config:
    ssl-protocols: "TLSv1.2 TLSv1.3"
    ssl-ciphers: "HIGH:!aNULL:!MD5"
    ssl-prefer-server-ciphers: "off"

  replicaCount: 1